import type { Metadata } from "next";
import Head from "next/head";
import { Jost } from "next/font/google";
import "./globals.css";
import { CustomProvider } from "@/provider/CustomProvider";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={jost.className}>
        <CustomProvider>{children}</CustomProvider>
      </body>
    </html>
  );
}
